import '../style/globals.css'
import { Noto_Serif_TC } from 'next/font/google'
import Header from '@/components/Header'

const noto_Serif_TC = Noto_Serif_TC({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${noto_Serif_TC.className} bg-primary dark:bg-secondary`}>
        <Header />
        <main className='w-full h-screen /mt-[100px]'>

          {children}
        </main>
      </body>
    </html>
  )
}
